# Heroku
export CYPRESS_HERO_USER=[USER_NAME]
export CYPRESS_HERO_PASS=[PASSWORD]

# Cypress Dasboard
export CYPRESS_DASHBOARD_ID=[CYPRESS PROJECT ID]
export CYPRESS_DASHBOARD_KEY=[CYPRESS DASHBOARD KEY]

# MYSQL DB
export CYPRESS_DB_USER=[DB USERNAME]
export CYPRESS_DB_PASSWORD=[DB PASSWORD]
export CYPRESS_DB_USER_LOCAL=[LOCAL DB USERNAME]
export CYPRESS_DB_PASSWORD_LOCAL=[LOCAL DB PASSWORD]
export CYPRESS_DB_USER_DEV=[DEV DB USERNAME]
export CYPRESS_DB_PASSWORD_DEV=[DEV DB PASSWORD]
