name: Cypress Automation
run-name: Cypress Automation ${{ github.sha }}

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'dev'
      
      #Workaround while understanding deployment_status
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'

      spec:
        type: choice
        description: Test File to run
        required: true
        default: all
        options: 
        - all
        - heroApp.cy.js
        - seleniumEasy.cy.js
      
      browser:
        type: choice
        description: Browser to use on the tests
        required: true
        default: chrome
        options: 
        - chrome
        - electron

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      # Setting environment
      - name: Set Up Environment
      # Both github.event.inputs.deployment and input.deployment should work
        run: |
          echo "TEST_ENVIRONMENT=${{ inputs.deployment == 'yes' && 'dev' || inputs.env}}" >> $GITHUB_ENV
          echo "SPEC_PATTERN=${{ inputs.spec == 'all' && '*.cy.js' || inputs.spec }}" >> $GITHUB_ENV
      
      # NPM Installation and Cypress execution
      - name: Cypress Execution
        uses: cypress-io/github-action@v4
        continue-on-error: true
        with:
          spec: '**/${{env.SPEC_PATTERN}}'
          ci-build-id: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          tag: 'cy'
          record: true
          browser: ${{ inputs.browser }}
          headed: false
          install: true
        env:
          CYPRESS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          CYPRESS_TEST_TRIGGER: ${{github.event_name}}
          CYPRESS_username: ${{ secrets.CYPRESS_username }}
          CYPRESS_password: ${{ secrets.CYPRESS_password }}
          CYPRESS_envKey: ${{env.TEST_ENVIRONMENT}}
      
      # Moving away from this but keeping as reference
      - name: Jira Synch Script
        if: false
        run: |
          python .github/scripts/cypress_jira_synch.py
        env: 
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          CYPRESS_DASHBOARD_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
